-- SQL Migration for user-created tables in Supabase
-- This file documents and provides the schema for the newly added tables with Foreign Key relationships

-- 1. profiles (Base table)
CREATE TABLE IF NOT EXISTS "profiles" (
    id UUID PRIMARY KEY,
    email TEXT NOT NULL,
    full_name TEXT,
    role TEXT,
    onboarding_completed BOOLEAN DEFAULT FALSE
);

-- 2. organizations
CREATE TABLE IF NOT EXISTS "organizations" (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id UUID REFERENCES "profiles"(id),
    business_name TEXT NOT NULL,
    business_type TEXT,
    currency TEXT DEFAULT 'GHS',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Business
CREATE TABLE IF NOT EXISTS "Business" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    owner_id UUID REFERENCES "profiles"(id),
    business_name TEXT,
    business_type TEXT,
    currency TEXT DEFAULT 'GHS',
    is_active BOOLEAN DEFAULT TRUE
);

-- 4. Branches
CREATE TABLE IF NOT EXISTS "Branches" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    business_id BIGINT REFERENCES "Business"(id),
    name TEXT,
    location TEXT,
    phone TEXT,
    is_active BOOLEAN DEFAULT TRUE
);

-- 5. Staff_profiles
CREATE TABLE IF NOT EXISTS "Staff_profiles" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_id UUID REFERENCES "profiles"(id),
    branch_id BIGINT REFERENCES "Branches"(id),
    job_title TEXT,
    salary NUMERIC
);

-- 6. Customers
CREATE TABLE IF NOT EXISTS "Customers" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    business_id BIGINT REFERENCES "Business"(id),
    name TEXT,
    phone TEXT,
    loyalty_points SMALLINT DEFAULT 0
);

-- 7. Products_Service
CREATE TABLE IF NOT EXISTS "Products_Service" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    business_id BIGINT REFERENCES "Business"(id),
    branch_id BIGINT REFERENCES "Branches"(id),
    name TEXT,
    category TEXT,
    price NUMERIC,
    cost_price NUMERIC,
    stock_quantity SMALLINT,
    is_service BOOLEAN DEFAULT FALSE
);

-- 8. Sales(orders/reciepts)
CREATE TABLE IF NOT EXISTS "Sales(orders/reciepts)" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    business_id BIGINT REFERENCES "Business"(id),
    branch_id BIGINT REFERENCES "Branches"(id),
    cashier_id BIGINT REFERENCES "Staff_profiles"(id),
    customer_id BIGINT REFERENCES "Customers"(id),
    total_amount NUMERIC,
    status TEXT
);

-- 9. SaaS Plans
CREATE TABLE IF NOT EXISTS "SaaS Plans" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    name TEXT,
    max_branches SMALLINT,
    max_staff SMALLINT,
    price NUMERIC
);

-- 10. Attendance(Payroll-ready)
CREATE TABLE IF NOT EXISTS "Attendance(Payroll-ready)" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    staff_id BIGINT REFERENCES "Staff_profiles"(id),
    date DATE,
    check_in TIMESTAMP,
    check_out TIMESTAMP
);

-- 11. Payment(Momo/Cash/Card)
CREATE TABLE IF NOT EXISTS "Payment(Momo/Cash/Card)" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    sale_id BIGINT REFERENCES "Sales(orders/reciepts)"(id),
    amount NUMERIC,
    reference TEXT,
    status TEXT
);

-- 12. Sale item
CREATE TABLE IF NOT EXISTS "Sale item" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    sale_id BIGINT REFERENCES "Sales(orders/reciepts)"(id),
    product_id BIGINT REFERENCES "Products_Service"(id),
    quantity SMALLINT,
    unit_price NUMERIC,
    subtotal NUMERIC
);

-- 13. Expenses
CREATE TABLE IF NOT EXISTS "Expenses" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    business_id BIGINT REFERENCES "Business"(id),
    branch_id BIGINT REFERENCES "Branches"(id),
    title TEXT,
    amount NUMERIC,
    category TEXT
);

-- 14. Subscription
CREATE TABLE IF NOT EXISTS "Subscription" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    business_id BIGINT REFERENCES "Business"(id),
    plan_id BIGINT REFERENCES "SaaS Plans"(id),
    status TEXT,
    start_date DATE,
    end_date DATE
);

-- 15. activity_logs
CREATE TABLE IF NOT EXISTS "activity_logs" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    business_id BIGINT REFERENCES "Business"(id),
    user_id UUID REFERENCES "profiles"(id),
    action TEXT,
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 16. payrolls
CREATE TABLE IF NOT EXISTS "payrolls" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    business_id BIGINT REFERENCES "Business"(id),
    month TEXT,
    total_amount NUMERIC,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 17. payslips
CREATE TABLE IF NOT EXISTS "payslips" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    payroll_id BIGINT REFERENCES "payrolls"(id),
    staff_id BIGINT REFERENCES "Staff_profiles"(id),
    gross_salary NUMERIC,
    deductions NUMERIC,
    net_salary NUMERIC
);

-- 18. receipts
CREATE TABLE IF NOT EXISTS "receipts" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    sale_id BIGINT REFERENCES "Sales(orders/reciepts)"(id),
    receipt_number TEXT,
    printed BOOLEAN DEFAULT FALSE
);

-- 19. refunds
CREATE TABLE IF NOT EXISTS "refunds" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    sale_id BIGINT REFERENCES "Sales(orders/reciepts)"(id),
    amount NUMERIC,
    reason TEXT,
    refunded_by UUID REFERENCES "profiles"(id)
);

-- 20. staff_loans
CREATE TABLE IF NOT EXISTS "staff_loans" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    staff_id BIGINT REFERENCES "Staff_profiles"(id),
    amount NUMERIC,
    balance NUMERIC,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 21. suppliers
CREATE TABLE IF NOT EXISTS "suppliers" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    business_id BIGINT REFERENCES "Business"(id),
    name TEXT,
    phone TEXT,
    email TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    status TEXT
);

-- 22. purchase_orders
CREATE TABLE IF NOT EXISTS "purchase_orders" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    business_id BIGINT REFERENCES "Business"(id),
    supplier_id BIGINT REFERENCES "suppliers"(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    total_cost NUMERIC
);

-- 23. purchase_order_items
CREATE TABLE IF NOT EXISTS "purchase_order_items" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    purchase_order_id BIGINT REFERENCES "purchase_orders"(id),
    product_id BIGINT REFERENCES "Products_Service"(id),
    quantity SMALLINT,
    cost_price NUMERIC,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 24. stock_transfers
CREATE TABLE IF NOT EXISTS "stock_transfers" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    business_id BIGINT REFERENCES "Business"(id),
    from_branch_id BIGINT REFERENCES "Branches"(id),
    to_branch_id BIGINT REFERENCES "Branches"(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    status TEXT
);

-- 25. stock_transfer_items
CREATE TABLE IF NOT EXISTS "stock_transfer_items" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    stock_transfer_id BIGINT REFERENCES "stock_transfers"(id),
    product_id BIGINT REFERENCES "Products_Service"(id),
    quantity SMALLINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 26. organization_members
CREATE TABLE IF NOT EXISTS "organization_members" (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES "profiles"(id),
    organization_id UUID NOT NULL REFERENCES "organizations"(id),
    role TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 27. customer_wallet
CREATE TABLE IF NOT EXISTS "customer_wallet" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id BIGINT REFERENCES "Customers"(id),
    balance NUMERIC,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 28. loyalty_transactions
CREATE TABLE IF NOT EXISTS "loyalty_transactions" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id BIGINT REFERENCES "Customers"(id),
    points SMALLINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 29. daily_summaries
CREATE TABLE IF NOT EXISTS "daily_summaries" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    business_id BIGINT REFERENCES "Business"(id),
    branch_id BIGINT REFERENCES "Branches"(id),
    date DATE,
    total_sales NUMERIC,
    total_expenses NUMERIC,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 30. discounts
CREATE TABLE IF NOT EXISTS "discounts" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    business_id BIGINT REFERENCES "Business"(id),
    name TEXT,
    type TEXT,
    value NUMERIC,
    is_active BOOLEAN DEFAULT TRUE
);

-- 31. sale_discounts
CREATE TABLE IF NOT EXISTS "sale_discounts" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    sale_id BIGINT REFERENCES "Sales(orders/reciepts)"(id),
    discount_id BIGINT REFERENCES "discounts"(id)
);

-- 32. notification
CREATE TABLE IF NOT EXISTS "notification" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID REFERENCES "profiles"(id),
    title TEXT,
    message TEXT,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 33. api_keys
CREATE TABLE IF NOT EXISTS "api_keys" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    business_id BIGINT REFERENCES "Business"(id),
    key TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 34. feature_flags
CREATE TABLE IF NOT EXISTS "feature_flags" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    plan_id BIGINT REFERENCES "SaaS Plans"(id),
    feature_key TEXT,
    is_enabled BOOLEAN DEFAULT FALSE
);

-- 35. inventory_movements
CREATE TABLE IF NOT EXISTS "inventory_movements" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    product_id BIGINT REFERENCES "Products_Service"(id),
    business_id BIGINT REFERENCES "Business"(id),
    change_type TEXT,
    quantity SMALLINT
);

-- 36. stores (Legacy/Linked to Branches)
CREATE TABLE IF NOT EXISTS "stores" (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id UUID REFERENCES "organizations"(id),
    branch_id BIGINT REFERENCES "Branches"(id),
    name TEXT NOT NULL,
    location TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 37. Permissions
CREATE TABLE IF NOT EXISTS "Permissions" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    name TEXT UNIQUE
);

-- 38. Business_roles
CREATE TABLE IF NOT EXISTS "Business_roles" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_id UUID REFERENCES "profiles"(id),
    business_id BIGINT REFERENCES "Business"(id),
    role TEXT
);

-- 39. role_permissions
CREATE TABLE IF NOT EXISTS "role_permissions" (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    role TEXT,
    permission_id BIGINT REFERENCES "Permissions"(id)
);

-- 40. sales (UUID based base table)
CREATE TABLE IF NOT EXISTS "sales" (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    amount NUMERIC NOT NULL
);
